# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-01 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import tribute.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('memories', models.CharField(choices=[('memories', 'Memories'), ('tributes', 'Tributes')], default='memories', max_length=1)),
                ('message', models.TextField()),
                ('posted_on', models.DateTimeField(verbose_name='Date Posted')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to=tribute.models.get_upload_file_name)),
                ('posted_on', models.DateTimeField(verbose_name='Date Posted')),
            ],
        ),
        migrations.CreateModel(
            name='Tribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('image', models.FileField(upload_to=tribute.models.get_upload_file_name)),
                ('posted_on', models.DateTimeField(verbose_name='Date Posted')),
            ],
        ),
    ]
