# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-01 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tribute', '0003_auto_20200801_0817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'verbose_name_plural': 'Memories'},
        ),
    ]
