# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-11 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribute', '0004_auto_20200801_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='appoved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tribute',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
