# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-11 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('memory_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PhotoApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('photo_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TributeApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('tribute_id', models.IntegerField()),
            ],
        ),
    ]
